### ISSUE TITLE
Install from HACS

### ISSUE THREAD

**Issue by alesnav** [algirdasc/hass-components#10]
Hello!
I tried to install Fluoreon component from HACS without success.
Is it possible? How can I do it?
This way, it will be always updated. If done manually, updates are manually applied too...
Thanks!

**Comment by rege245** [comment]
stopped working few days ago ;(

**Comment by algirdasc** [comment]
Duplicate of #13

**Comment by alesnav** [comment]
Hello @algirdasc ,

You have closed both issues, this one and #13 , but I guess this cannot be installed from HACS yet. Can you please reopen one of them to be able to track the status?

Thanks!
