### ISSUE TITLE
No module named 'PyCRC'

### ISSUE THREAD

**Issue by zaharpecherin** [algirdasc/hass-components#11]
I get errors: 
`Thermostat read_status error: No module named 'PyCRC'`
`Thermostat set_time error: No module named 'PyCRC'`

**Comment by hex** [comment]
I get the same error after upgrading to Home Assistant 0.107.6

**Comment by hex** [comment]
Managed to get it working by deleting the folder in `custom_components` restarting home assistant and adding it again. @zaharpecherin

**Comment by algirdasc** [comment]
Please update manifest.json from the repository.
