### ISSUE TITLE
Component might cause stability problems

### ISSUE THREAD

**Issue by andreadall** [algirdasc/hass-components#14]
Hello, thank you very much for the integration.
I would like to report this warning, I use hassio 107.7  and this message appears in the log:
"You are using a custom integration for floureon which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant."
Did I do something wrong? Personally I see no problems, thanks.

**Comment by algirdasc** [comment]
Hello, this is standard HASS warning message. You can ignore it, as it only warns that you are using not official integration.
