### ISSUE TITLE
No module named 'PyCRC'

### ISSUE THREAD

**Issue by dominikfe** [algirdasc/hass-components#16]
Hi!
The module is not working any more for me with 0.108.8. The log shows this line:
WARNING (MainThread) [custom_components.floureon] Thermostat 192.168.10.85 read_status error: No module named 'PyCRC'

Please help

**Comment by algirdasc** [comment]
Could you please download latest release from repository? This issue was already addressed and solved.

**Comment by dominikfe** [comment]
Tried but failing...what am I doing wrong?!

custom_components git clone https://github.com/algirdasc/hass-components/tree/master/floureon floureon
Cloning into 'floureon'...
fatal: repository 'https://github.com/algirdasc/hass-components/tree/master/floureon/' not found

**Comment by algirdasc** [comment]
You're using incorrect repository url. Use this: https://github.com/algirdasc/hass-components.git
