### ISSUE TITLE
 "ClimateDevice is deprecated, modify FloureonClimate to extend ClimateEntity"..

### ISSUE THREAD

**Issue by Asom-Velz** [algirdasc/hass-components#19]
HI

I receive the following warning after the latest update to 4.9

 "ClimateDevice is deprecated, modify FloureonClimate to extend ClimateEntity".

As I have read : There has been a change with naming the entities. For now they’re just a warning for the code owners to do some work. But after a certain update it will break.
All integrations in Home Assistant have been upgraded. Custom component authors need to do the migration themselves. You can do this while keeping backwards compatibility by using the following snippet:

https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/?fbclid=IwAR31aU6j2Z5zyX0DhwArOXHnI9YWMkcueVM7rRCHS1FfhFcLG4uitA528yM

This is my configuration.yaml - which was working fine before the update

climate:

# Configuration for Beok Thermostat
-  platform: floureon
   name: wall_th
   mac:  !secret wallth_mac
   host: !secret wallth_ip

Home Assistant version: 0.110.5
![midea](https://user-images.githubusercontent.com/65943619/83951028-7a7e8100-a837-11ea-82fc-e7f3aa1dbf79.jpg)

**Comment by algirdasc** [comment]
Did you tried updating component from repository to latest version?

**Comment by Asom-Velz** [comment]
Updated everything is working ok now!

Thank you
