### ISSUE TITLE
use_external_temp

### ISSUE THREAD

**Issue by liakoumedos** [algirdasc/hass-components#4]
Invalid config for [climate.floureon]: [use_extrenal_temp] is an invalid option for [climate.floureon]. Check: climate.floureon->use_extrenal_temp. (See ?, line ?)

this is the error that i am receiving .

climate:
  - platform: floureon
    name: ΘΕΡΜΑΝΣΗ
    mac: xx:xx:xx:xx:xx:xx
    host: 192.168.1.xxx
    use_extrenal_temp: false

this is my config

**Comment by algirdasc** [comment]
It was typo in documentation. Change `use_ext**re**nal_temp` to `use_external_temp`
