### ISSUE TITLE
Error on log. Not working

### ISSUE THREAD

**Issue by Boogs77** [algirdasc/hass-components#5]
I’ve copied 3 files from github in custom_components/floureon but after first reboot I get this error in log file:

ERROR (SyncWorker_1) [homeassistant.loader] Error parsing manifest.json file at /config/custom_components/floureon/manifest.json: Expecting value: line 7 column 1 (char 6)

**Comment by algirdasc** [comment]
Seems like `manifest.json` is downloaded / copied incorrectly. Try redownloading manifest.json
