### ISSUE TITLE
Add COOL mode to component

### ISSUE THREAD

**Issue by thundergreen** [algirdasc/hass-components#6]
Hi Watching your code you don't use the Cool mode. Would it be possible to integrate those. Likethis i could use it for my AC :)

**Comment by algirdasc** [comment]
Of course it would be possible. As I understand correctly the main difference would be only naming?

**Comment by thundergreen** [comment]
Not sure... I want to buy a floureon thermostat or another one with operation mode cool heat and auto and off .. to control my ac via my xiaomi remote component. which will send ir signals to my ac

**Comment by algirdasc** [comment]
I dont quite understand your plans or vision. Floureon or other broadlink based thermostat can control boiler / underfloor heating. If you could provide more details regarding AC thermostat, maybe I could help you somehow.
