### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by netruner** [algirdasc/hass-components#8]
I have C17.GH3 Floureon. Im instal to custom component.
And I have in state :
![Zrzut ekranu 2019-12-14 o 00 16 59](https://user-images.githubusercontent.com/2457018/70838115-0d99a980-1e07-11ea-830d-51aa7c99708f.png)

In GUI 

![Zrzut ekranu 2019-12-14 o 00 17 56](https://user-images.githubusercontent.com/2457018/70838147-2f932c00-1e07-11ea-9d8e-3e63ec58a361.png)

not working

**Comment by algirdasc** [comment]
Looks like it is not broadcom based thermostat.
