### ISSUE TITLE
Component causing big delay with any home assistant action

### ISSUE THREAD

**Issue by boutch** [algirdasc/hass-components#9]
Thank you for the great component.

I am using it to manage 7 underfloor heating wifi thermostat from the Floureon brand. I can see all the entities in home assistant and I can control them.

However, I soon as I add them, home assistant becomes very slow and any action have a lag 1-2sec. The home assistant logs are not showing any error or time out.

I am using Python 3.7.5 and a custom install on Ubuntu in a Python Virtual environment.

Any ideas?

climate:
  - platform: floureon
    name: LR Extension UF
    mac: 34:EA:34:78:XX:XX
    host: 192.168.30.167
    use_external_temp: false    
  - platform: floureon
    name: Living Room UF
    mac: 34:EA:34:78:XX:XX
    host: 192.168.30.73
    use_external_temp: false    
  - platform: floureon
    name: Bathroom UF
    mac: 34:EA:34:7A:XX:XX
    host: 192.168.30.38
    use_external_temp: true
  - platform: floureon
    name: Ensuite UF
    mac: 34:EA:34:7A:XX:XX
    host: 192.168.30.50
    use_external_temp: true
  - platform: floureon
    name: Parents UF
    mac: 34:EA:34:7A:XX:XX
    host: 192.168.30.44
    use_external_temp: false    
  - platform: floureon
    name: Kid1 UF
    mac: 34:EA:34:7A:XX:XX
    host: 192.168.30.125
    use_external_temp: false    
  - platform: floureon
    name: Kid2 UF
    mac: 78:0F:77:EB:XX:XX
    host: 192.168.30.184
    use_external_temp: false

**Comment by boutch** [comment]
Resolved

**Comment by privatesam** [comment]
I'm having the exact same problem - huge errors in the logs, slowdown on whole system and devices not responding etc - as soon as I take the component out of the config everything works fine.  how did you resolve this?
